//this file is autogenerated by tools/pivot_planner, don't edit this file, instead use pivotplanner to generate it.
enum BodyParts {
    BP_test_test_000 = 0,
    BP_test_test_001 = 1,
    BP_test_test_002 = 2,
    BP_test_test_003 = 3,
    BP_test_test_004 = 4,
    BP_test_test_005 = 5,
    BP_test_test_006 = 6,
    BP_test_test_007 = 7,
    BP_test_test_008 = 8,
    BP_test_test_009 = 9,
    BP_TOTAL = 10
};
internal void fill_generated_complex_values(ComplexFrame* generated_frames ) {
    generated_frames[BP_test_test_000] = (ComplexFrame){285, 74, 62, 61,55, 17, 60, 59, 190, 83, 87, 73, 88, 25};
    generated_frames[BP_test_test_001] = (ComplexFrame){221, 74, 64, 61,53, 17, 62, 59, 190, 83, 87, 73, 88, 25};
    generated_frames[BP_test_test_002] = (ComplexFrame){116, 67, 105, 61,12, 17, 103, 59, 190, 83, 87, 73, 88, 25};
    generated_frames[BP_test_test_003] = (ComplexFrame){360, 66, 108, 61,61, 17, 106, 59, 190, 83, 87, 73, 88, 25};
    generated_frames[BP_test_test_004] = (ComplexFrame){116, 0, 129, 67,61, 11, 127, 65, 190, 83, 87, 73, 88, 25};
    generated_frames[BP_test_test_005] = (ComplexFrame){360, 0, 128, 66,61, 17, 126, 64, 190, 83, 87, 73, 88, 25};
    generated_frames[BP_test_test_006] = (ComplexFrame){0, 76, 56, 61,61, 17, 54, 59, 190, 83, 87, 73, 88, 25};
    generated_frames[BP_test_test_007] = (ComplexFrame){245, 0, 115, 74,2, 4, 113, 72, 190, 83, 87, 73, 88, 25};
    generated_frames[BP_test_test_008] = (ComplexFrame){0, 0, 116, 76,1, 2, 114, 74, 190, 83, 87, 73, 88, 25};
    generated_frames[BP_test_test_009] = (ComplexFrame){56, 76, 56, 61,61, 17, 54, 59, 190, 83, 87, 73, 88, 25};
};
